### ISSUE TITLE
Difficult to do "vulnerable prior version" searches

### ISSUE THREAD

**Issue by sitsofe** [toolswatch/vFeed#41]
When using vFeed's search to check for NTP vulnerabilities a difficult case occurs:

```
# ./vfeedcli.py search cpe:/a:ntp:ntp:4.2.6

[+] Querying information for cpe:/a:ntp:ntp:4.2.6 ...
	 [-] Total Unique CVEs        [0] 
	 [-] Total Found CPEs         [0] 
[+] Nothing found in the database

# ./vfeedcli.py search CVE-2014-9295

[+] Querying information for CVE-2014-9295 ...
	[-] Multiple stack-based buffer overflows in ntpd in NTP before 4.2.8 allow remote attackers to execute arbitrary code via a crafted packet, related to (1) the crypto_recv function when the Autokey Authentication feature is used, (2) the ctl_putdata function, and (3) the configure function.

[INFO] Try vfeedcli.py export CVE-2014-9295 for more information !!

# ./vfeedcli.py search cpe:/a:ntp:ntp:4.2.7

[+] Querying information for cpe:/a:ntp:ntp:4.2.7 ...
	 [-] Total Unique CVEs        [5] 
	 [-] Total Found CPEs         [1] 
[+] Gathering information ... 
	[-] cpe:/a:ntp:ntp:4.2.7
		[-] CVE-2013-5211 | CVSS Base :5.0
			[->] The monlist feature in ntp_request.c in ntpd ....
			[!] 1 Metasploit Exploit(s) Found
			[!] 1 Exploit DB sploits Found
		[-] CVE-2014-9293 | CVSS Base :5.0
			[->] The config_auth function in ntpd in NTP ....
		[-] CVE-2014-9294 | CVSS Base :5.0
			[->] util/ntp-keygen.c in ntp-keygen in NTP before 4.2.7p230 ....
		[-] CVE-2014-9295 | CVSS Base :7.5
			[->] Multiple stack-based buffer overflows in ntpd in ....
		[-] CVE-2014-9296 | CVSS Base :5.0
			[->] The receive function in ntp_proto.c in ntpd ....
```

(http://www.eecis.udel.edu/~ntp/ntp_spool/ntp4/NEWS also confirms there are issues that affect 4.2.6).

It would be useful if there was a search feature that allowed you to find out if vulnerabilities affecting later versions also affect the version you are looking at...

**Comment by toolswatch** [comment]
On Sat, Jan 3, 2015 at 10:44 AM, Sitsofe Wheeler <notifications@github.com>
wrote:

> cpe:/a:ntp:ntp:4.2.7



See here
http://web.nvd.nist.gov/view/vuln/search-results?adv_search=true&cves=on&cpe_version=cpe:/a:ntp:ntp:4.2.6

There is no entry


Because the main CVE entry for vFeed is NVD.

**Comment by jeremylong** [comment]
NJ,

This is an issue I faced with [dependency-check](http://jeremylong.github.io/DependencyCheck/). If you look at [CVE-2014-9296](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-9296) you'll see that the vulnerable software is listed as "cpe:/a:ntp:ntp:4.2.7 and previous versions". If you look at the [2.0 schema](https://nvd.nist.gov/schema/nvd-cve-feed_2.0.xsd) of the [NVD XML data feeds](https://nvd.nist.gov/download.cfm#CVE_FEED) there is no flag for "all previous versions". However, if you look at the [1.2 schema](https://nvd.nist.gov/schema/nvdcve.xsd) you'll see that the vulnerable software section does contain the flag for "all previous versions". Dependency-check pulls both the 1.2 and 2.0 XML data feeds and correlates them so that I can get the 2.0 data with the all previous versions flag from 1.2. 

Querying against this can cause issues with displaying things incorrectly when there are multiple major versions and the bug was fixed at different points in each of the major version branches. I opened an issue against dependency-check earlier today for this [issue](https://github.com/jeremylong/DependencyCheck/issues/180).

Email me if you want to discuss this more.

Regards,

Jeremy

**Comment by sitsofe** [comment]
Jeremy:
Thanks for mentioning this. I can't find anything that says _why_ the "all previous versions" flag was removed from the 2.0 version of the schema (the closest thing I can find to an explanation of the changes is https://nvd.nist.gov/download-cve-2-0-changelog.cfm ).

If I'm understanding your explanation correctly, there's no (easy) programmatic way of determining if previous versions are affected if you are using only a 2.0 NVD data feed? To try and determine it you would have to do one or more of the following:
* Parse the English text for words along the lines of "and previous versions".
* Try and match the same package in the 1.2 version of the feed and check the ```prod/vers/prev``` attribute there.

Are vendors supposed to list old versions that are affected if they aren't maintained branches? Where are the guidelines for this written down? What do other database aggregation projects (e.g. OpenVAS) do?

Without the above I'm guessing the best you could do is some sort of crude version number scanning (but how to do this reliably in a world of packages with versions like 1.23_def-vendorhere-6) where a warning appears that a later version of the package with a vulnerability exists. Would that be feasilble?
