### ISSUE TITLE
Web application and API SOURCE

### ISSUE THREAD

**Issue by Antho59** [toolswatch/vFeed#66]
Hi, 

i'm wondering, i saw that some people spoke about meteor, a web app for vfeed, but i tested it and seems not to be finished, can you give us more information about web app for vfeed ? 

Second question, 

Is it possible to use vfeed's API to pull some Vuln (cve, cwe, etc) from private source ? or the only one source is your vfeed.tar.gz ? 

Thanks a lot

**Comment by UShan89** [comment]
Hi Antho59,

I started it a while back. Thank you for asking about it.

I am interested in finishing the UI quickly. Please do bear with me. One
thing that currently stops me is if I want to add the meteor source code to
vFeed or whether I want to start it as a separate repo. Never asked
@toolswatch NJ Ouchn.

Do you have suggestions? I will have this ready in a week from today.

**Comment by Antho59** [comment]
Thanks for your answer, 

Any suggestions about the web app functionality ? I have many :)

Is meteor the only one framework you could work with ? An another could maybe be more appreciate ? 

May could we talk about theses functionality in private ?

**Comment by toolswatch** [comment]
Hi guys,
Sai (Ushan89) is doing great to make this happening using the Meteor Framework. As for myself, i'm working on a Web Service based on Flask. Dont expect anything for now, as i'm still learning Flask. 
So, I'm as excited as you to see Ushan89 work.

Russ McRee has a well a Dashboard based on vFeed using the R language (https://github.com/holisticinfosec/vFeedViewer ).

**Comment by Antho59** [comment]
Seems to be nice, what about my second question guys ? 

Is it possible to feed mongodb with private source in additional of the vfeed.db ? API don't seem to be able to do that

**Comment by UShan89** [comment]
@Antho59 If you want to use the same database but have private information, you might want to have the information in a new collection. That way, vFeed updates would remain as is. 

On the question of web framework, mongoDB makes abstraction possible. Native data-types for supported languages is a great feature in mongoDB. 

Why Meteor? Use mongodb, use npm (node) packages, use any other javascript package and at the same time get it done fast. It is so easy to program with meteor. I've seen highschool kids pick up the framework and make productive apps in less than a week. (No intent to compare a person but it's just so easy with meteor). No extra programming for mobile-ready applications, it just happens by including a package. 

Flask (Python) as @toolswatch mentions is great too, except python + synchronous micro-framework means I better write quality&clean python code and make sure I can do asynchronous python programming. On the other hand, Meteor has reactivity many features baked-in making my life look easier. 

Once something is in mongo, the choices are purely unlimited. Java/PHP/Python/JavaScript/NodeJS/C/c++(Including legacy)/Ruby/Scala/C# even perl. 

The possibilites for webframework are unlimited. It all boils down to personal preferences and choices. I am advocating Meteor because I <3 `meteor`. Do you see that using code in meteor as a barrier?

**Comment by Antho59** [comment]
i don't know meteor so i don't know if all the web app functionalities i would like to have are possible to do, but if u tell me that u can do anything you wanna do, i trust you so don't matter the framework :)

**Comment by UShan89** [comment]
I've started the project at [vFeed-UI](https://github.com/UShan89/vFeed-UI.git) 

For features, please add them as issues.

**Comment by fastfire** [comment]
We (sec4u.co) have developed a php UI interface at http://www.sec4u.co/vfeed/search.php. We ask you to test the application and report any bugs or requests for new implementations with an email at team@sec4u.co or a message in this post. Thank you!

**Comment by UShan89** [comment]
@fastfire I just tried searching. Takes a short duration ( 5-8 seconds) but gives results sorted. This is good.
